### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by PeppoDevStudio** [Badbird5907/AntiCombatLog#16]
Hi, i have this error

[10:22:44 ERROR]: [Citizens] Cannot register a null trait. Was it registered properly?
[10:22:44 ERROR]: Could not pass event NPCDeathEvent to AntiCombatLog v2.2.7
java.lang.NullPointerException: Cannot invoke "net.badbird5907.anticombatlog.object.CombatNPCTrait.getXp()" because the return value of "net.citizensnpcs.api.npc.NPC.getTrait(java.lang.Class)" is null
        at net.badbird5907.anticombatlog.listener.NPCListener.onNpcDeath(NPCListener.java:20) ~[AntiCombatLog-2.2.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor999.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1886]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:286) ~[Citizens-2.0.30-b2888.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor599.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1886]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:916) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:929) ~[?:?]
        at net.citizensnpcs.nms.v1_19_R2.entity.EntityHumanNPC.a(EntityHumanNPC.java:148) ~[Citizens-2.0.30-b2888.jar:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1535) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1001) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1109) ~[?:?]
        at net.citizensnpcs.nms.v1_19_R2.entity.EntityHumanNPC.a(EntityHumanNPC.java:309) ~[Citizens-2.0.30-b2888.jar:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:403) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:212) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:203) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:297) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:233) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1294) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:755) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:732) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Badbird5907** [comment]
Use the latest version

Solved here: https://discord.com/channels/970357534189834301/1067851966367137792/1068659037899591821
Commit: ff7ec5c0bcb83efd8afecff29902a2e233a9fcc9

https://discord.badbird.dev/
