### ISSUE TITLE
Error - 1.19.4 NoClassDefFoundErrornet

### ISSUE THREAD

**Issue by Shanman150** [Badbird5907/AntiCombatLog#18]
Great plugin, I've used it for the last few years without issue. This year I went to update the plugins and I'm encountering repeating errors in the console as well as errors when a player dies. No NPC is created. I have troubleshooted by having:

1) Both plugins at their latest versions
2) The citizens2 plugin downgraded to the version we were using last summer
3) The versions currently recommended on the Spigot page: https://www.spigotmc.org/resources/anticombatlog.94540/
(AntiCombatLog 2.2.7, Citizens-2.0.30-b2816)

All of these still result in errors occurring once per second in the console and AntiCombatLog not functioning properly.

I assume this must be a 1.19.4 issue, given the lack of difference that it makes what version of the plugins I'm using?

Error in console:
[18.04 23:14:04] [Server] [WARN] [AntiCombatLog] Task #44 for AntiCombatLog v2.2.7 generated an exception
[18.04 23:14:04] [Server] java.lang.NoClassDefFoundErrornet/citizensnpcs/api/npc/NPCDataStore
[18.04 23:14:04] [Server] 	at net.badbird5907.anticombatlog.runnable.UpdateRunnable.run(UpdateRunnable.java:21) ~[AntiCombatLog-2.2.7.jar:?]
[18.04 23:14:04] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-514]
[18.04 23:14:04] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-514]
[18.04 23:14:04] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-514]
[18.04 23:14:04] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-514]
[18.04 23:14:04] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-514]
[18.04 23:14:04] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-514]
[18.04 23:14:04] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-514]
[18.04 23:14:04] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18.04 23:14:04] [Server] Caused byjava.lang.ClassNotFoundException: net.citizensnpcs.api.npc.NPCDataStore
[18.04 23:14:04] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
[18.04 23:14:04] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
[18.04 23:14:04] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[18.04 23:14:04] [Server] 	... more

**Comment by Shanman150** [comment]
I've discovered the probable source of the issue - I was using the old configs for both plugins which likely resulted in the errors. Regenerating the configs has resolved the issue on both newest versions - my mistake!

Closing this as it is no longer an issue.
